### ISSUE TITLE
INLA

### ISSUE THREAD

**Issue by stevencarlislewalker** [bbolker/mixedmodels-taskview#1]
Don't know if this matters, but `INLA` is not on `CRAN` so it maybe shouldn't be in the task view?

**Comment by bbolker** [comment]
actually, I think several of the task views have 'off-CRAN' sections, and I think it's a useful place to put this information ... (I'm glad you're looking at this, I was thinking this was a project I should get back to ...)  How's it going?  Do you want to skype/google+/whatever briefly sometime in the next couple of hours?

**Comment by stevencarlislewalker** [comment]
Fair enough.  I'm free to skype now if you like.
