### ISSUE TITLE
general machinery?

### ISSUE THREAD

**Issue by bbolker** [bbolker/mixedmodels-taskview#12]
I'm still torn about whether we should include more general engines (e.g. Stan, NIMBLE, greta, JAGS/BUGS, rethinking) and interfaces thereto in this Task View. Opinions?

**Comment by emitanaka** [comment]
I'm in favour of this. I notice there are already references to ASReml-R and INLA so it would be in a similar spirit as these to add others (except perhaps `greta` which could go under Convenience wrappers or Bayesian).

**Comment by bbolker** [comment]
There are a few separate (partly orthogonal) categories:

* on CRAN (`greta`, `rstan`, `cmdstanr`, `nimble`, `R2jags` etc. [`grep("jags|bugs", rownames(available.packages()), value = TRUE, ignore.case=TRUE)`] vs not (`INLA`, `ASReml-R`)
* FOSS vs not (ASReml-R)

The main distinction I was trying to make here is that these frameworks all require you to construct the model from a more basic level than just specifying response variables, fixed effects/RE structures etc.

**Comment by emitanaka** [comment]
I would say many of the mixed model R packages are in fact high-level interface or wrappers for R (`brms` for Stan, `R2jags` for jags, `greta` for TensorFlow, `INLA` for INLA, `ASReml-R` for ASReml standalone, etc). I think it makes more sense to give prominence to packages on CRAN (which I general assume is FOSS), and have well-known, but non-FOSS, ones (e.g. `ASReml`, `SAS`) at the bottom including any dependency on these (e.g. `asremlPlus`).

**Comment by bbolker** [comment]
closed in c35ccc4
