### ISSUE TITLE
Some suggestions (location-scale models, missing values, mbest, and information-theoretic methods)

### ISSUE THREAD

**Issue by wviechtb** [bbolker/mixedmodels-taskview#14]
The proposal is excellent! A mixed models task view is long overdue, I suspect in part since it's a rather substantial task. So thank you for tackling this.

One thing that immediately comes to mind is **location-scale models**, like Hedeker's stuff (e.g., https://doi.org/10.18637/jss.v052.i12) except that MIXREGLS isn't an R package (but could link to it under Other/Links: https://voices.uchicago.edu/hedeker/mixwild_mixregls/). But `glmmTMB` allows this via the `dispformula` argument for the error variance / dispersion parameter. I am not aware of any packages that also allow scale modeling of other variance components, but one might cobble something together via `OpenMx`. In any case, I think location-scale models should fall under **Specialized models** and `glmmTMB` should be mentioned there. 

Under **Missing values**, I would also mention `mice` there since it can do some multilevel imputation stuff. Also, `JointAI` and `mdmb` should be mentioned here as packages that go beyond the mice capabilities for mixed effects models.

Also, package `mbest` should be added. It fits hierarchical models using moment-based estimation. Could mention this under the Frequentist packages (it also does GLMMs), or alternatively under **Specialized models** but it's not really a different model per se, just an alternative to maximum likelihood estimation.

Since the group of people working with mixed effects models overlaps with people who may want to do model selection via information-theoretic methods, it might be worth mentioning packages like `glmulti` and `MuMIn` as well.

**Comment by bbolker** [comment]
I think these are all added. Please take a quick look and check/see if they seem to be added appropriately?  Thanks!

**Comment by wviechtb** [comment]
Looks good!

This one is also for location-scale models: https://cran.r-project.org/package=LMMELSM It is current archived, but should hopefully be revived soon.

**Comment by bbolker** [comment]
We should keep a list somewhere of "currently archived but useful if restored" and check it periodically with `available.packages()` ...

**Comment by wviechtb** [comment]
Also `gam()` from `mgcv` with the `gaulss` family can do a location-scale model (as mention in a Tweet just now: https://twitter.com/IsabellaGhement/status/1579922893458505729).
