### ISSUE TITLE
Multimembership models

### ISSUE THREAD

**Issue by palday** [bbolker/mixedmodels-taskview#17]
Should we mention these in the taskview? I'm only aware of two pieces of software supporting it:

- brms (cf. https://github.com/paul-buerkner/brms/issues/130)
- https://github.com/jvparidon/lmerMultiMember

**Comment by wviechtb** [comment]
Not on CRAN yet (but hopefully soon), but this one should be relevant as well: https://github.com/benrosche/rmm Just noting it here so we don't forget once it makes its way to CRAN.

**Comment by bbolker** [comment]
MCMglmm does multi-membership models too
