### ISSUE TITLE
scope for panel data models

### ISSUE THREAD

**Issue by emitanaka** [bbolker/mixedmodels-taskview#18]
Panel data models (to me) are essentially mixed models for econometricians (some discussion about this in Cross Validated [here](https://stats.stackexchange.com/questions/34642/difference-between-panel-data-mixed-model)). Would it make sense to include these here? I feel it does because for example `pglm::pglm()` is used quite often for analysis of count longitudinal data and while the motivation of these models are often driven by econometrics data, the models can be applicable beyond econometrics.

**Comment by wviechtb** [comment]
In principle, I think it would be appropriate to include this. But this overlaps with the "Panel data models" section of the [Econometrics task view](https://cran.r-project.org/web/views/Econometrics.html), which we might just end up reproducing. I think to avoid this overlap, we should just point people there.

**Comment by bbolker** [comment]
This is a good idea. If someone who knows a little more than I do about this area could add something appropriate ... ?

**Comment by bbolker** [comment]
Completed in 4215459566aee54fa9e41fcc2717dd0e3c4a07f1
