### ISSUE TITLE
Add lmmsolver

### ISSUE THREAD

**Issue by jpiaskowski** [bbolker/mixedmodels-taskview#7]
https://github.com/Biometris/LMMsolver

**Comment by jpiaskowski** [comment]
I can add this along with the packages mentioned by @zeileis [here](https://github.com/cran-task-views/ctv/issues/35).

**Comment by bbolker** [comment]
I think it's worth adding; not clear whether it goes in "fitting" or "specialized models"

**Comment by jpiaskowski** [comment]
That is tough....specialized models? It be considered an additive model, or a subsection on "sparse model matrices".
