### ISSUE TITLE
add 'marginaleffects'

### ISSUE THREAD

**Issue by jpiaskowski** [bbolker/mixedmodels-taskview#9]
[marginaleffects](https://cran.r-project.org/package=marginaleffects) (for prediction/estimation)

**Comment by bbolker** [comment]
There's a more general question here. Many of the "downstream" prediction/estimation/diagnostics/plotting packages can handle some subset of mixed-model packages. `broom.mixed` is really the only special one. This set springs to mind: `performance`, `effects`, `emmeans`, `ggeffects`, `DHARMa`, `marginaleffects`, `gtsummary`, `stargazer`, ... what should our rubric/criteria be for including these packages in this task view?

**Comment by jpiaskowski** [comment]
I'm not entirely certain, to be honest. It depends on the overall purpose of this CTV, I suppose? My view is that this should help others implement mixed models and extract needed output from them. I view `emmeans`, `marginaleffects`, etc as convenience wrappers for extracting BLUEs from mixed model objects. While it's possible to do that without those packages, they do make it easier.  I don't know what those other packages do (e.g. `performance`), but it seems like if a package solves a needed issue and has methods specifically written for mixed model objects (e.g. `merMod`), then their inclusion is warranted.

**Comment by bbolker** [comment]
added.
